services:
  - type: web
    name: travel-backend
    env: python
    buildCommand: cd django && pip install -r ../requirements.txt
    startCommand: gunicorn travelgo.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: travelgo.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: travel-db
          property: connectionString
    buildFilter:
      paths:
        - django/**

  - type: web
    name: travel-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    buildFilter:
      paths:
        - frontend/**
