# Generated by Django 5.2.3 on 2025-06-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='no_of_seat',
            field=models.PositiveBigIntegerField(default=40),
            preserve_default=False,
        ),
    ]
